### ISSUE TITLE
Fix Bugs

### ISSUE THREAD

**Issue by 2hmad** [gopulse/pulse#6]
### Issue Description

- [x] Export `prefix`, `router` fields in Group struct
- [x] `JSON` method should return value
- [x] `BodyParse` to get body of the request
- [x] Export `params` field in Context struct
- [ ] Handle if user write additionally `/` at the end of URL handle it 
- [x] Move `CORS` middleware from request to response headers
